FROM spark:latest
WORKDIR /opt/spark/
COPY test_job2.py /opt/spark/work-dir/

# docker build -t spark-image .
# docker tag spark-image lyabomyr/spark-image:latest;
# docker push lyabomyr/spark-image:latest;

