apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "spark-jo2b-test"
  namespace: airflow
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "lyabomyr/spark-image:latest"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/work-dir/test_job2.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    cores: 5
    instances: 5
    memory: "512m"
    labels:
      version: 3.1.1
