---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
  labels:
    app: airflow-dags
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: airflow-dags
    namespace: airflow
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/dags

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags
  namespace: airflow
  labels:
    app: airflow-dags
spec:
  volumeName: airflow-dags
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-requirements
  labels:
    app: airflow-requirements
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: airflow-requirements
    namespace: airflow
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/requirements.txt

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-requirements
  namespace: airflow
  labels:
    app: airflow-requirements
spec:
  volumeName: airflow-requirements
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi