kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_1"
    extraMounts:
      - hostPath: ./logs
        containerPath: /tmp/logs
      - hostPath: ../
        containerPath: /tmp/dags
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_2"
    extraMounts:
      - hostPath: ./logs
        containerPath: /tmp/logs
      - hostPath: ../
        containerPath: /tmp/dags
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node=worker_3"
    extraMounts:
      - hostPath: ./logs
        containerPath: /tmp/logs
      - hostPath: ../
        containerPath: /tmp/dags
